### ISSUE TITLE
Sublime Text does not render colors correctly on macOS

### ISSUE THREAD

**Issue by amckinlay** [dempfi/ayu#198]
Sublime Text does not do any color management on macOS, so color themes will look different depending on the specific monitor a user is using. See SublimeTextIssues/Core#880.

**Comment by dempfi** [comment]
Hi @amckinlay, I'm aware of the situation, however, I don't get what I can do to help improve the situation. I should say tho, ayu's colours were tested both on sRGB and P3 modes since 2016 and I try to keep them bright as promised in the readme 😉. Closing for now, if you think there's something to be done — please let me know.
