### ISSUE TITLE
CSS syntax highlighting is a mess

### ISSUE THREAD

**Issue by whatsnewsisyphus** [dempfi/ayu#202]
Element selectors are too close to properties in color
Numerical properties are too close to class selectors
All in all, it is not the best information hierarchy.
![Screenshot 2019-03-09 12 51 09](https://user-images.githubusercontent.com/454772/54075193-79445a00-426a-11e9-810c-e5c186701c1c.png)

Agila Dracula for Comparison, which is missing browser prefix highlighting, it would be nice if they were the same hue as a property but less saturated/light
![Screenshot 2019-03-09 16 41 12](https://user-images.githubusercontent.com/454772/54077699-33978980-428a-11e9-983f-4e2cad1221c6.png)

**Comment by dempfi** [comment]
Hi @whatsnewsisyphus, I tried in ayu to use the same pattern of selection for all languages, however CSS (XMLs too) are kinda illusive because of their declarative nature. I do consider getting back to them and doing some fixing, however it's really complicated at this stage with all the users who got used to the current colouring. If you do have some ideas, I would suggest you to open a PR. That way the discussion will be more to the point.

Anyhoo, closing the issue since there's nothing I can do in near future.

**Comment by dempfi** [comment]
Awesome, thx for the suggestion — will take a look.
