### ISSUE TITLE
Block caret color unreadable

### ISSUE THREAD

**Issue by mvllow** [dempfi/ayu#203]
Sublime v3200 introduced an official block caret. When using vim (either Vintage or ActualVim) the block caret is unreadable. This should be themeable now which is why I am raising an issue here - favourite theme! Will look into submitting a PR over the weekend if I can figure something out.

**Comment by pearofducks** [comment]
@mvllow - There's a new key - `block_caret` - that can be used to style this.

**Comment by dempfi** [comment]
@mvllow ayu's build system got updated and it should be considerably easier to contribute to it.

Regarding block caret, I looked into it yesterday and realized I don't really understand how it should behave and look since I never really used them. So yeah, input/PR from an experienced user would really help.

**Comment by mvllow** [comment]
Haven't done a public PR before but I'll try today!

This wasn't necessary in older versions of sublime because vim emulation created a "fake" block cursor using the normal cursor color.
