### ISSUE TITLE
[ST4] All syntax highlighting turns to gray (comment color) on defocus

### ISSUE THREAD

**Issue by kevinvalk** [dempfi/ayu#248]
Been using Ayu theme for a long time, big fan!

Lately I switched to Sublime Text 4 and noticed that the syntax highlighting turns "off" (i.e. everything is comment color gray) when focus is lost to the text window. This includes when focus is lost "internally" like opening the command pallet or selecting another tab (side-by-side).

![image](https://user-images.githubusercontent.com/3524694/120107502-88709480-c161-11eb-8438-54428c51deda.png)

I tested this for all Ayu Themes and they all behave the same. I made sure this this is not a ST4 issue by switching back to original theme, but there it is not an issue.

![image](https://user-images.githubusercontent.com/3524694/120107552-b655d900-c161-11eb-8ca2-d9dbf9b499a6.png)

**Comment by JxDannyxJ** [comment]
Since no one answered yet. This might be related to the property `inactive_selection_foreground` set in the globals of the [ayu-mirage.sublime-color-scheme](https://github.com/dempfi/ayu/blob/master/ayu-mirage.sublime-color-scheme). It colors the current selection [greyish](https://www.w3schools.com/colors/colors_picker.asp) if not in focus. You can unset this property or select a matching color

**Comment by kevinvalk** [comment]
ST4 release fixes this #251 
https://github.com/dempfi/ayu/pull/251/files#diff-877cf8378e65112efe387977699a1bba136418669c5c64509fe3100b909b5e59L22
