### ISSUE TITLE
Color scheme changes in 1.0.0 @ 2021-07-02

### ISSUE THREAD

**Issue by exitlol** [dempfi/ayu#250]
I want my old color schemes back. How can I revert the ugly purple-ish colors to the original yellow-orangeish one without reverting the version?

Please, please keep the option with the original color theme. I want my 0.20.0 colors back.

**Comment by dempfi** [comment]
@exitlol it seems you are referring to the changes in https://github.com/ayu-theme/vscode-ayu. To get a previous version: 
- Clone the repo;
- Go to commit `b922db9dfc0af45926b04e01f9cbebe502966b84`;
- Install dependencies with `yarn` in the source directory;
- Create a new build via `yarn build`;
- Create a new package via `yarn package`;
- Open vscode extensions panel;
- Click on the dots and select "Install from VSIX"
- Pick the package you've created in the previous step;

That said, I encourage you to give it a go — some beta testers also were troubled by sudden changes but came to love them after a week of usage. In general, v1 contains a lot of small contrast and usability improvements.

**Comment by emlautarom1** [comment]
I second this. Any chance for a toggle? Sadly, VSCode does not provide an easy way to install an old version of a theme without resorting to building it locally (as suggested above).

**Comment by emlautarom1** [comment]
Sure, take a look:

![Screenshot from 2021-09-03 15-59-12](https://user-images.githubusercontent.com/31224949/132054113-e5775ed3-f89f-4053-b648-edb93de777a5.png)

This is a JSON file (VSCode's `settings.json`). The background of the closing bracket (last line) is green, same as for both `false`. Text used to be yellow, and now is pink-ish. AFAIK,  these are intentional changes. Nevertheless, I found that you can roll back to a previous version directly from VSCode without needing to build the theme from source.

![Screenshot from 2021-09-03 16-02-36](https://user-images.githubusercontent.com/31224949/132054439-132aa237-f2b6-4173-a043-927819e3b8e1.png)

I'll keep using version 0.20.2 for now.

**Comment by sobolevn** [comment]
Repost from https://github.com/ayu-theme/vscode-ayu/issues/123
<img width="1280" alt="Снимок экрана 2021-09-03 в 22 06 44" src="https://user-images.githubusercontent.com/4660275/132055455-d5a073ff-7c62-4fde-9112-f2170440e876.png">

**Comment by dempfi** [comment]
Thank you @emlautarom1 and @sobolevn for screenshots. Let's move discussion to https://github.com/ayu-theme/vscode-ayu/issues/123 as this repo is for different project.

**Comment by dempfi** [comment]
Closing this in favor of https://github.com/ayu-theme/vscode-ayu/issues/123
