### ISSUE TITLE
Scroll bar has  wrong colour

### ISSUE THREAD

**Issue by prog-rajkamal** [dempfi/ayu#79]
![image](https://cloud.githubusercontent.com/assets/11518519/21292465/0c3165dc-c52d-11e6-870c-f79f0f1a6a78.png)

As you can see in the screenshot. Scroll bars are of wrong color in the light theme.

**Comment by Dezeter** [comment]
Yeah, scroll is broken 
![2016-12-18_18-05-13](https://cloud.githubusercontent.com/assets/1019521/21294399/bee85978-c54c-11e6-9e4f-f0da5004ab95.gif)

**Comment by qaraluch** [comment]
every time there is some problems with update... 
I've got the same with console message: "no such prop setting".

**Comment by dempfi** [comment]
@Dezeter, @prog-rajkamal and @qaraluch I suppose you guys experience issue on windows, right? Will investigate the root cause and either fix the bug or revert the commit.

@qaraluch 
> every time there is some problems with update...
Unfortunately I don't have enough time to test on 3 operation systems and since this theme is released under MIT you are free to contribute by testing on windows new versions before releases

**Comment by ilyes-kechidi** [comment]
@dempfi  same thing on linux KDE 
![screenshot_20161218_184727](https://cloud.githubusercontent.com/assets/482942/21295316/97e41320-c552-11e6-8204-b42ca0ffd6f9.png)

**Comment by prog-rajkamal** [comment]
@dempfi I used it on windows 8.1.
